spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: localhost
    port: 25

google:
  client:
    id: "${GOOGLE_CLIENT_ID:test-client-id}"  # .env 없으면 기본값
    secret: "${GOOGLE_CLIENT_SECRET:test-client-secret}"  # .env 없으면 기본값
  redirect:
    uri: "http://localhost:8080/test/callback"

jwt:
  secret: "dGhpc0lzQVZlcnlTZWN1cmVTZWNyZXRLZXlGb3JURVNUSU5HUHVycG9zZXNJdE11c3RCZUF0TGVhc3QzMkJ5dGVzTG9uZ1RvU2F0aXNmeUpXVEhNQUNSZXF1aXJlbWVudHM="
  expiration: 86400000
  refresh-expiration: 604800000
