spring:
  application:
    name: vims
  
  # WebSocket Configuration
  websocket:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
  
  # Database Configuration (H2 for development)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  
  h2:
    console:
      enabled: true
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  
  # Redis Configuration for session management
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

# Server Configuration
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Kurento Media Server Configuration
kurento:
  ws:
    uri: ws://localhost:8888/kurento

# COTURN STUN/TURN Server Configuration
webrtc:
  stun:
    urls: stun:localhost:3478
  turn:
    urls: turn:localhost:3478
    username: turnuser
    credential: turnpass

# Logging Configuration
logging:
  level:
    com.vims: DEBUG
    org.kurento: DEBUG
    org.springframework.web.socket: DEBUG

